### ISSUE TITLE
Add boxplot in RNA-seq module

### ISSUE THREAD

**Issue by Liuy12** [Liuy12/bringd32biology#1]
I suggest add boxplot using metricsgraphics library http://hrbrmstr.github.io/metricsgraphics/, which is based on metricsgraphics.js (Built on top of D3). I already generated density plot based on metricsgraphics library, but right now, they still didn't support explicit variable specification in some of their functions (Need to file a issue) 

Things to work on 
- add box plot 

Report bugs about 
- d3heatmap, got some of the heatmap cut out 
- metricsgraphics, didn't support explict variable in mjs_add_line function

**Comment by Liuy12** [comment]
@saucedaf

**Comment by saucedaf** [comment]
Great point but quick question...how do these graphs look so beautiful?

**Comment by Liuy12** [comment]
Because they are interactive bro!
